### ISSUE TITLE
18 spotlight_searches

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#11]
!ruby/hash:ActionController::Parameters
to
!ruby/hash:ActiveSupport::HashWithIndifferentAccess

add columns:
"default_index_view_type" varchar, no default, null
"search_box" boolean DEFAULT 0,

**Comment by eltiffster** [comment]
CREATE TABLE: 
```
  `default_index_view_type` varchar(255),
  `search_box` boolean DEFAULT 0,
```
Replaced `!ruby/hash:ActionController::Parameters` with `!ruby/hash:ActiveSupport::HashWithIndifferentAccess`

[spotlight18.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c5885d69685ab00119e838e/125516c66e82c728ace21e0d46fb8495378e8aae87fdee1be611b2843b492d762a10e17132d0bb2dba152c580d0949ff105e0e44fcfb892ca2bf6f78db4e17ff933c0120996048e6edc00db513bb27814e80b2b58e4cc1ef3a25e4888f5d73.txt)

**Comment by eltiffster** [comment]
Changed above to default null
