### ISSUE TITLE
20 spotlight_solr_document_sidecars

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#12]
!ruby/hash:ActionController::Parameters
to
!ruby/hash:ActiveSupport::HashWithIndifferentAccess

add columns:
"resource_id" integer DEFAULT NULL, split from document_id column
"resource_type" varchar DEFAULT NULL, null
"index_status" blob(10485760) DEFAULT NULL, null

**Comment by eltiffster** [comment]
CREATE TABLE:
```
  `resource_id` int(11) DEFAULT NULL,
  `resource_type` varchar DEFAULT NULL,
  `index_status` blob(10485760) DEFAULT NULL,
```

Replaced `!ruby/hash:ActionController::Parameters` with `!ruby/hash:ActiveSupport::HashWithIndifferentAccess`

**Comment by eltiffster** [comment]
For new sql dump: see note to 16 resources
