### ISSUE TITLE
23 users

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#14]
remove columns:
`current_sign_in_at` datetime DEFAULT NULL,
  `last_sign_in_at` datetime DEFAULT NULL,
  `current_sign_in_ip` varchar(255) DEFAULT NULL,
  `last_sign_in_ip` varchar(255) DEFAULT NULL,

**Comment by eltiffster** [comment]
Deleted guest users and renumbered other users (42 total), dropped columns (lines 91-95). Waffle wouldn't let me upload a .sql file so it's a .txt here.

[spotlight23-new.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c5885d69685ab00119e838e/125516c66e82c728ace21e0d46fb8495378e8aae87fded10e953f5836b0a65633b0ba92e7391a172fd1723040a5849a5130e5817adffd82ba6b43c778e5558e5807f4366846c4ff8e7df46f554f832815d84beb68b49c4e13e27e78d864c3b1e050ac4.txt)

**Comment by eltiffster** [comment]
Deleted guest users, removed columns (lines 91-96)

[spotlight23-new.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c5885d69685ab00119e838e/125516c66e82c728ace21e0d46fb8495378e8aae87fded10e953f5836b0a65633b0ba92e7391a172fd1723040a5849a5130e5817adffd82ba6b43c778e5558e5807f4366846c4ff8e7df46f554f832815d84b1b68b49c4e13e27e48388493c1c060ac4.txt)

**Comment by eltiffster** [comment]
Caught some syntax errors: the last inserted value should have ; and there is a guest line missing ``   `guest` tinyint(1) DEFAULT '0', `` in CREATE TABLE.
