### ISSUE TITLE
10 spotlight_exhibits

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#15]

**Comment by eltiffster** [comment]
(line 22) `theme` varchar(255) DEFAULT NULL,

**Comment by eltiffster** [comment]
line 22 `` `theme`  varchar(255) DEFAULT NULL, ``

**Comment by eltiffster** [comment]
Added theme/varchar line and added null values to existing exhibits.

[spotlight10.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c5885d69685ab00119e838e/125516c66e82c728ace21e0d46fb8495378e8aae87fdee13e611b2843b492d762a10e17132d0bb2dba152c580d0949ff105e0e44fcfb892ca2bf6f78db4e17ff933c0120996048e6edc00db513bb27814e80b2b5894ec1e93d23e782875d73.txt)
