### ISSUE TITLE
06 spotlight_blacklight_configuration

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#7]
!ruby/hash:ActionController::Parameters
to
!ruby/hash:ActiveSupport::HashWithIndifferentAccess

**Comment by eltiffster** [comment]
Replaced `!ruby/hash:ActionController::Parameters` with
`!ruby/hash:ActiveSupport::HashWithIndifferentAccess`

**Comment by eltiffster** [comment]
Same thing re DEFAULT NULL
