### ISSUE TITLE
11 spotlight_featured_images

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#8]
add
"iiif_region" varchar, no default, NULL
"iiif_manifest_url" varchar,  no default, NULL
"iiif_canvas_id" varchar,  no default, NULL
"iiif_image_id" varchar,  no default, NULL
"iiif_tilesource" varchar, no default, '/images/#{ID_GOES_HERE}/info.json'

**Comment by eltiffster** [comment]
in CREATE TABLE :
```
  `iiif_manifest_url` varchar(255) NULL,
  `iiif_canvas_id` varchar(255) NULL,
  `iiif_image_id` varchar(255) NULL,
  `iiif_tilesource` varchar(255),
```

Added `` , "/images/#{id}/info.json"`` to each row

[spotlight11-new.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c5885d69685ab00119e838e/125516c66e82c728ace21e0d46fb8495378e8aae87fdee12e953f5836b0a65633b0ba92e7391a172fd1723040a5849a5130e5817adffd82ba6b43c778e5558e5807f4366846c4ff8e7df46f554f832815d84beb68b49c4e13e2ce18c8e4f3f160d0ac4.txt)

**Comment by eltiffster** [comment]
Had to insert new featured images (id 328-334) since this is how Spotlight uploads & stores avatar images. The avatar_id attribute in contacts refers to the featured image ID.

**Comment by eltiffster** [comment]
For new SQL dump:

The spotlight14032019_11.new.sql file has images up to 400 (including contact images). Hopefully you still have the script for changing resources into featured images?

In terms of the actual files (in public/...featured_image/image), we're missing 393-400. Here is a list of the folder and files that go in them:

393    'IMG_0702.JPG'
394    'Huculak_Portrait_Book_sm.jpg'
395    'bohlman.jpg'
396    'bohlman.jpg'
397    'lara-wilson.jpg'
398     'Huculak_Redwood_Portrait_socialmedia.jpg'
399     'Priestley-068551.jpg'
400     'computecanada.jpg'
